feat: add all shards download & unzip script
allenai/mmc4 pull request #2
Opened 2023-04-17 03:49 UTC by Luodian

1. feat: add all shards download & unzip script for no_facev2 and no_face_corev3
2. update corresponding readme to execute the command 

> written with the help of GPT-4, and checked validity by luodian (drluodian@gmail.com)

2023-05-05 19:38 UTC, VegB requested changes
Hi Luodian,

Thank you so much for providing the downloading scripts!! 
I left a few comments for minor changes, would you mind solving them before we merge it to the main stream?

2023-05-05 19:38 UTC, VegB commented on scripts/download_images.py
Might need to update/revert the changes as there are some more recent edits on this file

2023-05-06 05:48 UTC, Luodian commented on scripts/download_images.py
> Hi Luodian,
> 
> Thank you so much for providing the downloading scripts!! I left a few comments for minor changes, would you mind solving them before we merge it to the main stream?

I alddressed the requested changes. There for making in total 9 commits, if it bothers, you can squash them and then merge.

2023-05-06 05:52 UTC, Luodian commented
I already checked the scripts that they can download the mmc4  zipped jsonls, and then use `download_image.py` to download corresponding images then use [convertion script](https://github.com/mlfoundations/open_flamingo/blob/main/open_flamingo/train/convert_mmc4_to_wds.py) to create the required shards file for training MMC4 on Openflamingo.

2023-05-06 23:19 UTC, VegB approved these changes

2023-05-07 01:08 UTC, merged

2023-05-07 01:09 UTC, jmhessel commented
Thanks @Luodian and @VegB !